In [7]:
import numpy as np

In [8]:
a = [[11,12,13],[21,22,23],[31,32,33]]

a = np.array(a)
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [9]:
# ndim numero de dimensiones
a.ndim

2

In [10]:
# shape numnero de listas y tamaño de cada lista
a.shape

(3, 3)

In [11]:
# numero total de elemtos
a.size

9

In [12]:
# producto de Hadamard

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

resultado = A * B

print(resultado)  # [4, 10, 18]


[ 4 10 18]


In [13]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])