In [53]:
import numpy as np

In [54]:
a = np.array([0,1,2,3,4])

In [55]:
# access the data via index
a[1]

1

In [56]:
type(a)

numpy.ndarray

In [57]:
# size numero de alementos
a.size

5

In [58]:
# ndim numero de dimensiones o ranking de arrays
a.ndim

1

In [59]:
# shape es un tupla que indica tamaño y numero de dimensiones
a.shape

(5,)

In [60]:
#cambiar un valor del array

c = np.array([20,1,2,3,4])
#c:array([20,1,2,3,4])
c[0] =100
c



array([100,   1,   2,   3,   4])

In [61]:
d = c[1:4]
d

array([1, 2, 3])

In [62]:
# agragar varios valores
c[3:5] = 300,400
c

array([100,   1,   2, 300, 400])

In [63]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [64]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [65]:
3+2*2


7

In [66]:
int(3.2)

3

In [67]:
A='1234567'
A[1::2]

'246'

In [68]:
Name="Michael Jackson"
Name.find('el')

5

In [70]:
F="You are wrong"
F.upper()

'YOU ARE WRONG'

In [71]:
 A=((11,12),[21,22])
 A[1]

[21, 22]

In [72]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [76]:
V={'A','B','C'}
V.add('C')
V

{'A', 'B', 'C'}

In [77]:
x="Go"

if(x!="Go"):

    print('Stop')

else:

    print('Go ')

print('Mike')

Go 
Mike


In [79]:
for n in range(3):

    print(n)

0
1
2


In [80]:
for n in range(3):

    print(n+1)

1
2
3


In [81]:
def Add(x,y):

    z=y+x

    return(y)

Add('1','1')

'1'

In [82]:
class Points(object):

    def __init__(self,x,y):

        self.x=x

        self.y=y

    def print_point(self):

        print('x=',self.x,' y=',self.y)

p1=Points(1,2)

p1.print_point()





x= 1  y= 2


In [83]:
class Points(object):

    def __init__(self,x,y):

        self.x=x

        self.y=y

    def print_point(self):

        print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2
