In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3,4])

In [4]:
# access the data via index
a[1]

2

In [5]:
type(a)

numpy.ndarray

In [6]:
# size numero de alementos
a.size

5

In [7]:
# ndim numero de dimensiones o ranking de arrays
a.ndim

1

In [8]:
# shape es un tupla que indica tamaño y numero de dimensiones
a.shape

(5,)

In [11]:
#cambiar un valor del array

c = np.array([20,1,2,3,4])
#c:array([20,1,2,3,4])
c[0] =100
c



array([100,   1,   2,   3,   4])

In [13]:
d = c[1:4]
d

array([1, 2, 3])

In [14]:
# agragar varios valores
c[3:5] = 300,400
c

array([100,   1,   2, 300, 400])